// Code generated by protoc-gen-go. DO NOT EDIT.
// source: net/grpc/errorDetail.proto

package grpc

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Content struct {
	Data                 []byte   `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	ContentType          string   `protobuf:"bytes,2,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Content) Reset()         { *m = Content{} }
func (m *Content) String() string { return proto.CompactTextString(m) }
func (*Content) ProtoMessage()    {}
func (*Content) Descriptor() ([]byte, []int) {
	return fileDescriptor_f4eac1d3c7642b3c, []int{0}
}

func (m *Content) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Content.Unmarshal(m, b)
}
func (m *Content) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Content.Marshal(b, m, deterministic)
}
func (m *Content) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Content.Merge(m, src)
}
func (m *Content) XXX_Size() int {
	return xxx_messageInfo_Content.Size(m)
}
func (m *Content) XXX_DiscardUnknown() {
	xxx_messageInfo_Content.DiscardUnknown(m)
}

var xxx_messageInfo_Content proto.InternalMessageInfo

func (m *Content) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *Content) GetContentType() string {
	if m != nil {
		return m.ContentType
	}
	return ""
}

type ErrorDetail struct {
	Domain               string   `protobuf:"bytes,1,opt,name=domain,proto3" json:"domain,omitempty"`
	Content              *Content `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ErrorDetail) Reset()         { *m = ErrorDetail{} }
func (m *ErrorDetail) String() string { return proto.CompactTextString(m) }
func (*ErrorDetail) ProtoMessage()    {}
func (*ErrorDetail) Descriptor() ([]byte, []int) {
	return fileDescriptor_f4eac1d3c7642b3c, []int{1}
}

func (m *ErrorDetail) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ErrorDetail.Unmarshal(m, b)
}
func (m *ErrorDetail) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ErrorDetail.Marshal(b, m, deterministic)
}
func (m *ErrorDetail) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ErrorDetail.Merge(m, src)
}
func (m *ErrorDetail) XXX_Size() int {
	return xxx_messageInfo_ErrorDetail.Size(m)
}
func (m *ErrorDetail) XXX_DiscardUnknown() {
	xxx_messageInfo_ErrorDetail.DiscardUnknown(m)
}

var xxx_messageInfo_ErrorDetail proto.InternalMessageInfo

func (m *ErrorDetail) GetDomain() string {
	if m != nil {
		return m.Domain
	}
	return ""
}

func (m *ErrorDetail) GetContent() *Content {
	if m != nil {
		return m.Content
	}
	return nil
}

func init() {
	proto.RegisterType((*Content)(nil), "ocf.cloud.kit.net.grpc.pb.Content")
	proto.RegisterType((*ErrorDetail)(nil), "ocf.cloud.kit.net.grpc.pb.ErrorDetail")
}

func init() { proto.RegisterFile("net/grpc/errorDetail.proto", fileDescriptor_f4eac1d3c7642b3c) }

var fileDescriptor_f4eac1d3c7642b3c = []byte{
	// 207 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x4f, 0x3b, 0x4b, 0xc5, 0x30,
	0x14, 0xa6, 0x22, 0xf7, 0x72, 0xd3, 0x4e, 0x19, 0xa4, 0x3a, 0xd5, 0x8a, 0xd0, 0xc5, 0x13, 0xd0,
	0x51, 0x07, 0xf1, 0xf1, 0x07, 0x82, 0x93, 0x8b, 0xa4, 0x69, 0x5a, 0x43, 0xdb, 0x9c, 0x10, 0x4e,
	0x87, 0xfe, 0x7b, 0x69, 0x4c, 0x71, 0x72, 0x39, 0x9c, 0xd7, 0xf7, 0x62, 0x57, 0xce, 0x90, 0x18,
	0x82, 0xd7, 0xc2, 0x84, 0x80, 0xe1, 0xcd, 0x90, 0xb2, 0x13, 0xf8, 0x80, 0x84, 0xfc, 0x12, 0x75,
	0x0f, 0x7a, 0xc2, 0xa5, 0x83, 0xd1, 0x12, 0x38, 0x43, 0xb0, 0x7d, 0x82, 0x6f, 0xeb, 0x67, 0x76,
	0x7c, 0x45, 0x47, 0xc6, 0x11, 0xe7, 0xec, 0xbc, 0x53, 0xa4, 0xca, 0xac, 0xca, 0x9a, 0x42, 0xc6,
	0x9e, 0x5f, 0xb3, 0x42, 0xff, 0x9e, 0xbf, 0x68, 0xf5, 0xa6, 0x3c, 0xab, 0xb2, 0xe6, 0x24, 0xf3,
	0xb4, 0xfb, 0x58, 0xbd, 0xa9, 0x35, 0xcb, 0xdf, 0xff, 0x14, 0xf9, 0x05, 0x3b, 0x74, 0x38, 0x2b,
	0xeb, 0x22, 0xcf, 0x49, 0xa6, 0x89, 0x3f, 0xb1, 0x63, 0x42, 0x45, 0x92, 0xfc, 0xbe, 0x86, 0x7f,
	0x5d, 0x41, 0xb2, 0x24, 0x77, 0xc8, 0xcb, 0xed, 0xe7, 0xcd, 0x60, 0xe9, 0x7b, 0x69, 0x41, 0xe3,
	0x2c, 0x06, 0xbc, 0x43, 0xdd, 0x8b, 0xd1, 0x92, 0xd8, 0x53, 0x3f, 0x6e, 0xa5, 0x3d, 0xc4, 0xbc,
	0x0f, 0x3f, 0x01, 0x00, 0x00, 0xff, 0xff, 0xd9, 0x74, 0x4a, 0xe8, 0x0d, 0x01, 0x00, 0x00,
}
